apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config-pvc
  namespace: home-assistant
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: ha-config-pv
  resources:
    requests:
      storage: 5Gi
