#!/usr/bin/env bash
# Write /etc/rancher/k3s/config.yaml from environment variables.
#
# Use this instead of editing config.yaml directly so credentials are never
# stored in a file that might be shared or accidentally committed.
#
# Usage:
#   sudo \
#     ETCD_S3_ACCESS_KEY=AKIAxxxxxxxx \
#     ETCD_S3_SECRET_KEY=xxxxxxxx \
#     ./scripts/configure-k3s.sh
#
# Optional env (all have defaults matching the live cluster):
#   ETCD_S3_BUCKET    cloudless-etcd-snapshots
#   ETCD_S3_REGION    us-east-1
#   ETCD_S3_FOLDER    etcd
#   TLS_SAN_VIP       192.168.1.200
#   TLS_SAN_LAN       192.168.1.128
#   DATA_DIR          /srv/dev-disk-by-uuid-a9a5a108-8095-4b7b-8011-716889995cd7/k3s
#
# After writing the config, restart k3s to apply:
#   sudo systemctl restart k3s

set -euo pipefail

: "${ETCD_S3_ACCESS_KEY:?ETCD_S3_ACCESS_KEY must be set}"
: "${ETCD_S3_SECRET_KEY:?ETCD_S3_SECRET_KEY must be set}"

ETCD_S3_BUCKET="${ETCD_S3_BUCKET:-cloudless-etcd-snapshots}"
ETCD_S3_REGION="${ETCD_S3_REGION:-us-east-1}"
ETCD_S3_FOLDER="${ETCD_S3_FOLDER:-etcd}"
TLS_SAN_VIP="${TLS_SAN_VIP:-192.168.1.200}"
TLS_SAN_LAN="${TLS_SAN_LAN:-192.168.1.128}"
DATA_DIR="${DATA_DIR:-/srv/dev-disk-by-uuid-a9a5a108-8095-4b7b-8011-716889995cd7/k3s}"

if [[ ${EUID} -ne 0 ]]; then
  echo "run as root (sudo)" >&2; exit 1
fi

CONFIG=/etc/rancher/k3s/config.yaml
install -d -m 0755 /etc/rancher/k3s

# Back up existing config if present
if [[ -f "${CONFIG}" ]]; then
  cp "${CONFIG}" "${CONFIG}.bak.$(date +%Y%m%dT%H%M%S)"
  echo "[configure-k3s] backed up existing config"
fi

cat > "${CONFIG}" <<EOF
# Generated by scripts/configure-k3s.sh on $(date -u +%FT%TZ)
# Edit via: sudo ETCD_S3_ACCESS_KEY=… ETCD_S3_SECRET_KEY=… ./scripts/configure-k3s.sh
# See k3s/config.example.yaml for field reference.

# Keep k3s data on the 120 GB USB drive, not the SD card.
data-dir: ${DATA_DIR}

cluster-init: true
secrets-encryption: true
flannel-backend: wireguard-native

tls-san:
  - "${TLS_SAN_VIP}"
  - "${TLS_SAN_LAN}"

kube-apiserver-arg:
  - "service-node-port-range=1000-32767"

etcd-snapshot-schedule-cron: "0 */6 * * *"
etcd-snapshot-retention: 3
etcd-s3: true
etcd-s3-bucket: ${ETCD_S3_BUCKET}
etcd-s3-region: ${ETCD_S3_REGION}
etcd-s3-folder: ${ETCD_S3_FOLDER}
etcd-s3-access-key: ${ETCD_S3_ACCESS_KEY}
etcd-s3-secret-key: ${ETCD_S3_SECRET_KEY}
etcd-s3-insecure: false

etcd-arg:
  - heartbeat-interval=300
  - election-timeout=3000
  - quota-backend-bytes=2147483648
  - auto-compaction-retention=1h
  - auto-compaction-mode=periodic

kubelet-arg:
  - max-pods=110
  - eviction-hard=memory.available<200Mi
  - image-gc-high-threshold=80
  - image-gc-low-threshold=70
  - system-reserved=cpu=200m,memory=200Mi
  - kube-reserved=cpu=200m,memory=300Mi
EOF

chmod 600 "${CONFIG}"
echo "[configure-k3s] wrote ${CONFIG} (mode 600)"
echo "[configure-k3s] restart k3s to apply: sudo systemctl restart k3s"
