#!/usr/bin/env bash
# Install and configure keepalived on omv or omv-ha.
#
# keepalived holds a virtual IP (VIP) shared by both Pis. When the MASTER
# goes down the VIP moves to the BACKUP within seconds, so user traffic to
# cloudless.gr keeps serving without a manual DNS change.
#
# Topology
#   omv    (Pi 5, 192.168.1.128) — MASTER, priority 101
#   omv-ha (Pi 4, 192.168.1.130) — BACKUP, priority 90
#   VIP    192.168.1.200 on eth0
#
# The MASTER is the node that answers the VIP under normal conditions. When
# k3s stops on the MASTER, the health-check script exits non-zero, keepalived
# lowers the effective priority below the BACKUP's, and the VIP migrates.
#
# Prerequisites (on both nodes):
#   sudo apt-get install -y keepalived
#   (this script installs it if missing)
#
# Usage (run as root on the target Pi):
#   sudo ./scripts/install-keepalived.sh
#
# Env (all have defaults):
#   ROLE         master | backup  (auto-detected from hostname if omitted)
#   VIP          virtual IP to hold  (default: 192.168.1.200)
#   IFACE        LAN interface       (default: eth0)
#   VRID         VRRP virtual router id 1-255, must match on both nodes (default: 51)
#   AUTH_PASS    VRRP auth password ≤8 chars (default: kp-omv51)
#   MASTER_IP    LAN IP of the MASTER node    (default: 192.168.1.128)
#   BACKUP_IP    LAN IP of the BACKUP node    (default: 192.168.1.130)

set -euo pipefail

VIP="${VIP:-192.168.1.200}"
IFACE="${IFACE:-eth0}"
VRID="${VRID:-51}"
AUTH_PASS="${AUTH_PASS:-kp-omv51}"
MASTER_IP="${MASTER_IP:-192.168.1.128}"
BACKUP_IP="${BACKUP_IP:-192.168.1.130}"

if [[ ${EUID} -ne 0 ]]; then
  echo "run as root (sudo)" >&2; exit 1
fi

# --- auto-detect role from hostname ---
if [[ -z "${ROLE:-}" ]]; then
  hn="$(hostname -s)"
  case "${hn}" in
    omv-ha*) ROLE=backup ;;
    omv*)    ROLE=master ;;
    *)
      echo "Cannot auto-detect role from hostname '${hn}'." >&2
      echo "Set ROLE=master or ROLE=backup explicitly." >&2
      exit 1
      ;;
  esac
fi
ROLE="${ROLE,,}"
[[ "${ROLE}" == "master" || "${ROLE}" == "backup" ]] || {
  echo "ROLE must be 'master' or 'backup', got '${ROLE}'" >&2; exit 1
}

if [[ "${ROLE}" == "master" ]]; then
  STATE=MASTER
  PRIORITY=101
  PEER_IP="${BACKUP_IP}"
else
  STATE=BACKUP
  PRIORITY=90
  PEER_IP="${MASTER_IP}"
fi

log() { printf '[keepalived] %s\n' "$*"; }

log "role=${ROLE} state=${STATE} priority=${PRIORITY} vip=${VIP} iface=${IFACE}"

# --- install ---
if ! command -v keepalived >/dev/null 2>&1; then
  log "installing keepalived"
  apt-get update -qq
  apt-get install -y -qq keepalived
else
  log "keepalived already installed ($(keepalived --version 2>&1 | head -1))"
fi

# --- write health-check script ---
cat > /etc/keepalived/check_k3s.sh <<'EOF'
#!/bin/sh
# Exit 0 = healthy (hold the VIP); exit 1 = unhealthy (yield the VIP).
systemctl is-active --quiet k3s
EOF
chmod +x /etc/keepalived/check_k3s.sh
log "wrote /etc/keepalived/check_k3s.sh"

# --- write keepalived.conf ---
cat > /etc/keepalived/keepalived.conf <<EOF
# Generated by install-keepalived.sh — $(date -u +%FT%TZ)
# Role: ${ROLE} on $(hostname -s)

global_defs {
  router_id $(hostname -s)
  script_user root
  enable_script_security
}

vrrp_script chk_k3s {
  script       "/etc/keepalived/check_k3s.sh"
  interval     2    # check every 2 s
  fall         2    # 2 consecutive failures → yield VIP
  rise         2    # 2 consecutive successes → take VIP
  weight       -20  # subtract 20 from priority when unhealthy
}

vrrp_instance VI_1 {
  state            ${STATE}
  interface        ${IFACE}
  virtual_router_id ${VRID}
  priority         ${PRIORITY}
  advert_int       1

  unicast_src_ip   $(ip -4 addr show "${IFACE}" | awk '/inet /{split($2,a,"/"); print a[1]; exit}')
  unicast_peer {
    ${PEER_IP}
  }

  authentication {
    auth_type PASS
    auth_pass ${AUTH_PASS}
  }

  virtual_ipaddress {
    ${VIP}/24 dev ${IFACE}
  }

  track_script {
    chk_k3s
  }

  notify_master "/bin/sh -c 'logger -t keepalived VIP_ACQUIRED_on_\$(hostname -s)'"
  notify_backup "/bin/sh -c 'logger -t keepalived VIP_RELEASED_on_\$(hostname -s)'"
  notify_fault  "/bin/sh -c 'logger -t keepalived VIP_FAULT_on_\$(hostname -s)'"
}
EOF
log "wrote /etc/keepalived/keepalived.conf"

# --- enable + (re)start ---
systemctl enable keepalived
systemctl restart keepalived
sleep 2

state_out="$(journalctl -u keepalived -n 5 --no-pager 2>/dev/null || true)"
if systemctl is-active --quiet keepalived; then
  log "keepalived is running"
  if [[ "${STATE}" == "MASTER" ]]; then
    if ip addr show "${IFACE}" | grep -q "${VIP}"; then
      log "VIP ${VIP} is held on this node ✓"
    else
      log "WARNING: VIP not yet on this interface — check logs:"
      echo "${state_out}"
    fi
  else
    log "BACKUP node — VIP will be held by the MASTER (${PEER_IP})"
  fi
else
  log "ERROR: keepalived failed to start. Last journal lines:"
  echo "${state_out}"
  exit 1
fi

log "done. Verify on both nodes:"
log "  ip addr show ${IFACE} | grep '${VIP}'"
log "  journalctl -u keepalived -f"
